---
sidebar: sidebar 
permalink: concept_overview_dashboard.html 
keywords: overview, provision, dashboard, widget, watchlist 
summary: Proporciona información sobre el panel, las listas de observación y los widgets. 
---
= Obtenga más información sobre las listas de seguimiento en Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las listas de observación se utilizan para acceder a los sistemas preseleccionados dentro de Digital Advisor de forma rápida y sencilla. Si ve a un cliente determinado o un conjunto de sistemas con frecuencia, le recomendamos que cree listas de observación. Puede crear hasta 100 listas de comprobaciones y cada lista de comprobaciones puede contener hasta 15.000 sistemas por categoría o 500 sistemas por números de serie.

Cuando accede por primera vez al Asesor Digital, puede crear una lista de comprobaciones o buscar un nombre de cliente, nombre de sitio, nombre de grupo, StorageGRID, nombre de host, clúster, número de serie, ID del sistema o suscripción de Keystone.

También debe tener en cuenta los colores aplicados a las tarjetas, que indican la gravedad y el tipo de riesgos.
