---
sidebar: sidebar 
permalink: concept_get_started_with_health_check_dashboard.html 
keywords: activeiq, health check, health, hca, health check dashboard, autosupport, autosupport adoption, recommended configuration, best practices, support, support and entitlements, support contract, contracts, active contracts, expired contracts, nearing-expiration, key recommendations, recommendations, digital advisor, features, recommended software 
summary: Proporciona información sobre el panel, las puntuaciones de estado, las funciones y los widgets. 
---
= Comience a usar el panel de control de salud de Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Este panel proporciona un resumen de un vistazo de la base instalada mediante los siguientes widgets:

* *AutoSupport Adoption*: Muestra el número y el porcentaje de sistemas con AutoSupport activado. También puedes ver los sistemas marcados como ‘Declined', aquellos con *HTTPS* y *AutoSupport on Demand* activados, así como *Loss of Signal* para los sistemas que han dejado de enviar datos de AutoSupport en los últimos 7 días. Para ver tu puntuación de la comprobación de estado e información sobre los sistemas de tu base instalada, selecciona el widget *AutoSupport Adoption*.
* *Configuración recomendada*: Muestra los sistemas que son compatibles y no compatibles según el widget *Configuración recomendada*. Le ayuda a tomar medidas para garantizar que sus sistemas estén bien configurados en la base instalada. Puede ver la calificación proporcionada en el panel y tomar las medidas necesarias en función de las recomendaciones clave que se proporcionen por orden de prioridad.
* *Software recomendado*: Muestra una lista consolidada de todas las actualizaciones de software y firmware y recomendaciones de moneda. Es posible ver los sistemas con la función AutoSupport habilitada que debería tener versiones de software o firmware mínimas o más recientes.
* *Soporte y derechos*: Muestra los contratos de soporte que han caducado y aquellos que están a punto de caducar en un plazo de entre 6 y 12 meses. Muestra las plataformas, discos y estanterías cuyo soporte ha finalizado, el cumplimiento de los derechos, las caducidades pendientes y los casos en los que el fin del soporte para la plataforma y el hardware no es aplicable. Puedes ver la puntuación de la evaluación de estado que aparece en el panel de control y tomar acciones según las recomendaciones clave, que se muestran en orden de prioridad. Para ver información detallada sobre los contratos de soporte, selecciona el widget *Soporte y derechos*. También puedes renovar tus contratos de soporte usando este widget.
* *Mejores prácticas*: Muestra la puntuación de comprobación de estado evaluando los atributos de mejores prácticas del sistema de almacenamiento: Vulnerabilidades de rendimiento y eficiencia, disponibilidad y protección, capacidad, configuración y seguridad. Las prácticas recomendadas de NetApp ayudan a sostener el estado del sistema, que optimiza el rendimiento de la base instalada.
* *Casos técnicos*: Le ofrece una vista detallada del historial técnico de su caso, por tipo de caso y estado abierto o cerrado, en intervalos de tiempo seleccionables.  Puede acceder a grupos de casos, así como ver detalles de casos a través de link:https://mysupport.netapp.com//["Sitio de soporte de NetApp"^] u otros portales de casos.

