---
sidebar: sidebar 
permalink: concept_working_with_inventory_file.html 
keywords: inventory file, file format 
summary: Proporciona información acerca del trabajo con el archivo de inventario. 
---
= Actualice el archivo de inventario para la actualización del firmware AFF y FAS
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El archivo de inventario consta de los LIF de administración del clúster de los sistemas que pueden optar a las actualizaciones de firmware. Contiene la lista de clústeres con información de nombre de archivo del firmware de disco y bandeja donde sea aplicable.

Para la actualización del firmware del procesador de servicio, los nombres de host de nodos y la IP de SP/BMC se incluyen en el archivo de inventario.



== Formato de archivo de inventario

A continuación se muestra un formato de archivo de inventario con actualizaciones de disco y de firmware de bandeja:

[listing]
----
clusters:
  - clustername: <cluster management LIF-1>
    disk_fw_file: all.zip
    shelf_fw_file: all_shelf_fw.zip

  - clustername: <cluster management LIF-2>
    disk_fw_file: all.zip
    sp_nodes:
    - hostname: <node hostname 1>
      sp_fw_file: SP_FW_308-03990_11.5.zip
      sp_fw_type: bmc
      sp_fw_ver: '11.5'
      sp_ip: <BMC IP>
    - hostname: <node hostname 2>
      sp_fw_file: SP_FW_308-03991_5.8.zip
      sp_fw_type: sp
      sp_fw_ver: '5.8'
      sp_ip: <SP IP>
----
En el ejemplo, las actualizaciones de firmware de la bandeja y del disco son aplicables en las actualizaciones de firmware del clúster-1 y del disco, y del SP/BMC se aplican en el clúster-2.



== Elimine un clúster del archivo de inventario

En caso de que no desee aplicar actualizaciones de firmware en un clúster determinado, puede quitar el clúster del archivo de inventario.

Por ejemplo, si no desea aplicar actualizaciones de firmware de disco en clúster-2, puede quitarlo del archivo de inventario con el siguiente comando:

[listing]
----
clusters:
  - clustername: <cluster management LIF-1>
    disk_fw_file: all.zip
    shelf_fw_file: all_shelf_fw.zip
----
Puede observar que se han eliminado todos los datos del clúster-2.

Si desea aplicar solo las actualizaciones de firmware del disco en cluster-1 y no las actualizaciones de firmware de la bandeja, puede hacerlo mediante el siguiente comando:

[listing]
----
clusters:
  - clustername: <cluster management LIF-1>
    disk_fw_file: all.zip
----
Puede ver que la clave y el valor _shelf_fw_File_ se han eliminado del cluster-1.


NOTE: No se admite la adición manual de clústeres o controladoras.
