---
sidebar: sidebar 
permalink: concept_understand_activeiq_features.html 
keywords: digital advisor, features, upgrade, support offering 
summary: Proporciona información sobre el panel, las listas de observación, las funciones y los widgets. 
---
= Comprender las funciones de Digital Advisor
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Puede ver el estado general de su sistema de almacenamiento, información de alto nivel sobre el estado del sistema, inventario, planificación, actualizaciones e información valiosa a nivel de lista de observación mediante Digital Advisor.

Cuando accede a Digital Advisor por primera vez, puede crear una lista de observación o buscar un cliente, nombre de sitio, nombre del grupo, StorageGRID, nombre de host, Clúster, número de serie o ID del sistema.

También debe tener en cuenta los colores aplicados a las tarjetas, que indican la gravedad y el tipo de riesgos.

Las siguientes son algunas de las características de Digital Advisor:

* Vea varias listas de observación, información práctica y útil de un vistazo
* Obtenga información sobre todos los riesgos de su sistema de almacenamiento y las acciones que se deben adoptar para mitigar los riesgos
* Reduzca los riesgos con Active IQ Unified Manager
* Actualice su sistema de almacenamiento
* Vea la relación de eficiencia del almacenamiento, el espacio lógico utilizado, el espacio físico utilizado y los datos totales ahorrados para los sistemas de almacenamiento que ejecutan ONTAP 9.1 y una versión posterior
* Analice el rendimiento de sus dispositivos de almacenamiento viendo el formato gráfico de los datos de rendimiento
* Obtenga información acerca del hardware y el software que han caducado o que están cerca de caducar en los próximos 6 meses
* Actualice el firmware de ONTAP con Ansible
* Obtenga información detallada acerca de los sistemas que han superado el 90 % de la capacidad o que están cerca del 90 %
* Consulte información detallada sobre la configuración física y lógica, incluido un resumen de la configuración del clúster y del nodo, la información de nivel y volumen local, la interfaz de red y puerto, un diagrama de pila con detalles sobre los discos y bandejas, y unas pocas visualizaciones de cables
* Proporcione información e información de toda la pila que sean beneficiosas para la solución de problemas, las evaluaciones de actualizaciones, la validación de soluciones y la migración
* Compruebe la compatibilidad de los hosts y proporcione recomendaciones de actualización para los sistemas operativos, las controladoras y el firmware del host
* Llegue exactamente a lo que desea encontrar de una manera más rápida y inteligente



NOTE: Puede actualizar la oferta de soporte desde el widget *Configuración* del panel del sistema para obtener información sobre la base instalada y recibir asistencia personalizada.
