---
sidebar: sidebar 
permalink: concept_overview_storage_efficiency.html 
keywords: overview, storage efficiency, deduplication, compression 
summary: Proporciona información sobre el seguimiento de la eficiencia de su sistema de almacenamiento. 
---
= Comprender la eficiencia del almacenamiento
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
La consola de eficiencia del almacenamiento muestra la proporción de eficiencia del almacenamiento, el espacio lógico utilizado, el espacio físico utilizado y los datos totales ahorrados para los sistemas de almacenamiento que ejecutan ONTAP 9.1 y versiones posteriores. La ratio de eficiencia y el ahorro se pueden ver con y sin las copias Snapshot para sistemas AFF, sistemas no AFF, o ambos. Puede ver la información de eficiencia del almacenamiento a nivel de clúster o de nodo.

El ahorro total en el almacenamiento del cliente puede verse por función de eficiencia, como la deduplicación de volúmenes, la compresión de volúmenes, la compactación, los volúmenes FlexClone y las copias Snapshot. También puede ver los 5 sistemas de almacenamiento principales con la mejor ratio de eficiencia.

video::8Ge3_0qlyxA[youtube,width=848,height=480]