---
sidebar: sidebar 
permalink: concept_understand_activeiq_features.html 
keywords: digital advisor, features, upgrade, support offering 
summary: Proporciona información sobre el panel, las listas de observación, las funciones y los widgets. 
---
= Comprender las funciones de Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede ver el estado general de su sistema de almacenamiento, información de alto nivel sobre el estado del sistema, inventario, planificación, actualizaciones e información valiosa a nivel de lista de observación mediante Digital Advisor.

Cuando accede a Digital Advisor por primera vez, puede crear una lista de observación o buscar un cliente, nombre de sitio, nombre del grupo, StorageGRID, nombre de host, Clúster, número de serie o ID del sistema.

También debe tener en cuenta los colores aplicados a las tarjetas, que indican la gravedad y el tipo de riesgos.

Las siguientes son algunas de las características de Digital Advisor:

* Vea varias listas de comprobaciones, vistas de información prácticas y útiles de un vistazo.
* Obtenga información sobre todos los riesgos para su sistema de almacenamiento y las acciones para mitigar los riesgos.
* Reduzca los riesgos con Active IQ Unified Manager.
* Actualice su sistema de almacenamiento.
* Consulte la puntuación de sostenibilidad y el uso previsto de energía, carbono directo y calor. Según la puntuación de sostenibilidad, evalúe la eficiencia general de sus sistemas de almacenamiento y alinéese con las acciones recomendadas por NetApp para mejorar la puntuación. link:concept_understand_sustainability_dashboard.html["Leer más"].
* Vea la relación de reducción de datos, el espacio lógico utilizado, el espacio físico utilizado y los datos totales ahorrados para sistemas de almacenamiento que ejecutan ONTAP 9,1 y versiones posteriores.
* Analice el rendimiento de sus dispositivos de almacenamiento visualizando el formato gráfico de los datos de rendimiento.
* Obtenga información acerca del hardware y el software que han caducado o están próximos a su caducidad en los próximos 6 meses.
* Actualice el firmware de ONTAP con Ansible.
* Obtenga detalles sobre los sistemas que han superado el 90 % de su capacidad o que se acercan al 90 % de su capacidad.
* Consulte información de configuración lógica y física detallada, entre la que se incluye un resumen de la configuración del clúster y el nodo, la información de nivel y volumen local, la información de puerto e interfaz de red, un diagrama de pila con información sobre los discos y las bandejas, y algunas visualizaciones de cables.
* Proporcionar información e información entre pilas que sean beneficiosas para la solución de problemas, las evaluaciones de actualización, la validación de soluciones y la migración.
* Compruebe la compatibilidad de los hosts y proporcione recomendaciones de actualización para los sistemas operativos del host, los controladores y .
* Llega exactamente a lo que quieres encontrar de una manera más inteligente y rápida.



NOTE: Puede actualizar la oferta de soporte desde el widget *Configuración* del panel del sistema para obtener información sobre la base instalada y recibir asistencia personalizada.
