---
sidebar: sidebar 
permalink: concept_autosupport.html 
keywords: AutoSupport 
summary: Proporciona una descripción general de AutoSupport. 
---
= Obtenga más información sobre AutoSupport en Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AutoSupport es un mecanismo de telemetría que supervisa de forma proactiva el estado del sistema y envía automáticamente a NetApp datos de configuración, estado, rendimiento y eventos del sistema.

El soporte técnico de NetApp utiliza estos datos para acelerar el diagnóstico y la resolución de problemas, y Digital Advisor para detectar y evitar de manera proactiva posibles problemas. También se puede enviar a su organización de soporte interna y a un partner de soporte.


NOTE: Digital Advisor muestra los datos relacionados con AutoSupport sólo para sistemas cuyos datos AutoSupport tengan menos de 60 días de antigüedad.

Para los sistemas ONTAP, AutoSupport se habilita de forma predeterminada cuando se configura el sistema de almacenamiento por primera vez. Usted debe link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/GUID-91C43742-E563-442E-8161-17D5C5DA8C19.html["Configure AutoSupport"^] En los sistemas ONTAP para controlar cómo se envía la información de AutoSupport al soporte técnico y a su organización de soporte interna.

Si no desea habilitar AutoSupport, puede usar la función de carga de AutoSupport para cargar manualmente datos de AutoSupport para recibir recomendaciones e información sobre el ecosistema de almacenamiento.


NOTE: Los datos de AutoSupport no incluyen datos de usuario.

Si quiere más información sobre AutoSupport, consulte la documentación correspondiente:

* link:https://docs.netapp.com/us-en/ontap/system-admin/manage-autosupport-concept.html["ONTAP (FAS y AFF)"^]
* link:https://docs.netapp.com/us-en/storagegrid-117/admin/what-is-autosupport.html["StorageGRID"^]
* link:https://docs.netapp.com/us-en/e-series-santricity/sm-support/autosupport-feature-overview.html["SANtricity (E-Series y EF-Series)"^]
* link:https://docs.netapp.com/us-en/solidfire-active-iq/concept-active-iq-learn-about-active-iq.html["Element (NetApp HCI y SolidFire)"^]
* link:https://www.netapp.com/pdf.html?item=/media/10438-tr-4444pdf.pdf["Informe técnico: ONTAP AutoSupport y AutoSupport On Demand"^]
* link:https://www.netapp.com/pdf.html?item=/media/10439-tr4688pdf.pdf["Informe técnico: Seguridad y privacidad de los datos de telemetría de NetApp"^]

