---
sidebar: sidebar 
permalink: digital-advisor-integration-with-bluexp.html 
keywords: digital advisor, integration, bluexp 
summary: 'El asesor digital (anteriormente asesor digital de Active IQ) ahora está totalmente integrado con BlueXP. Ahora puede gestionar los clústeres y acceder a todas las funciones de Digital Advisor desde la interfaz de usuario de BlueXP.' 
---
= Integración con Digital Advisor con BlueXP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El asesor digital (anteriormente asesor digital de Active IQ) ahora está totalmente integrado con BlueXP. Ahora puede gestionar los clústeres y acceder a todas las funciones de Digital Advisor desde la interfaz de usuario de BlueXP.

Con BlueXP, los expertos en TECNOLOGÍA y arquitectos de cloud pueden gestionar de forma centralizada su infraestructura multicloud híbrida. Todo lo que necesita es una cuenta del sitio de soporte de NetApp (NSS) para acceder al asesor digital en BlueXP.



== Descripción general de la integración

A partir de noviembre de 2022, se alentará a los usuarios de Digital Advisor a utilizar Digital Advisor en BlueXP. Desde BlueXP, tendrá acceso a la misma interfaz de Digital Advisor a la que está acostumbrado, además de mucho más. BlueXP permite crear y administrar el almacenamiento en nube (por ejemplo, Cloud Volumes ONTAP), utilizar los servicios de datos de NetApp (por ejemplo, Backup en nube) y controlar muchos dispositivos de almacenamiento local y periférico.



== Acceder a Digital Advisor en BlueXP

Puede acceder a Digital Advisor desde BlueXP para gestionar su clúster.

.Pasos
. Abra un explorador web y vaya a. https://cloudmanager.netapp.com/app-redirect/active-iq["BlueXP"^]
. Seleccione *Iniciar sesión con sus credenciales del sitio de soporte de NetApp* e introduzca sus credenciales.
+
Si anteriormente creó un inicio de sesión de BlueXP con un correo electrónico y una contraseña, deberá continuar utilizando esa opción de inicio de sesión en su lugar.

. Cuando se le solicite, inicie sesión con sus credenciales del sitio de soporte de NetApp.
+
Este inicio de sesión es diferente del inicio de sesión completado en el paso 2. En el paso 2, ha iniciado sesión en la plataforma BlueXP. Ahora inicia sesión en Digital Advisor.



*resultado*

Se muestran todas sus listas de observación y configuraciones existentes y ahora puede utilizar el asesor digital como suele hacer.



== Más información sobre BlueXP

https://docs.netapp.com/us-en/cloud-manager-family/concept-overview.html["Vaya a la documentación de BlueXP para obtener más información"^]
