---
sidebar: sidebar 
permalink: learn-about-sustainability.html 
keywords: activeiq, sustainability, sustainability score, sustainability dashboard, benefits, ontap, netapp console 
summary: Proporciona información sobre sostenibilidad que le permite reducir el consumo de energía y le permite trabajar hacia sus objetivos ambientales. 
---
= Aprenda sobre sostenibilidad con Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La sostenibilidad le permite reducir el consumo de energía y le permite trabajar para alcanzar sus objetivos medioambientales.  Esto le permite alinear sus sistemas de almacenamiento con prácticas ecológicas y alcanzar los objetivos de sostenibilidad.

Puedes consultar la puntuación de sostenibilidad y el consumo previsto de energía, las emisiones directas de carbono y el calor en el panel de control de sostenibilidad. Puedes ajustar el porcentaje de reducción de carbono para sitios específicos. También puedes consultar la puntuación de sostenibilidad a nivel de clúster. En función de la puntuación de sostenibilidad, puedes evaluar la situación de sostenibilidad y aplicar las acciones recomendadas de NetApp para mejorar la puntuación. Para obtener más información sobre el panel de control de sostenibilidad, ve a link:sustainability-dashboard-overview.html["Información general del panel de sostenibilidad"].


NOTE: La sostenibilidad es compatible con los sistemas Cloud Volumes ONTAP, AFF (A-Series y C-Series), E-Series, FAS y StorageGRID.

Puede ver el siguiente vídeo para comprender el panel de control de Sustainability:

video::yNRHeOvbGX8[youtube,width=848,height=480]


[[benefits-of-sustainability]]
== Beneficios de la sostenibilidad

La sostenibilidad ofrece los siguientes beneficios:

* Acelere el rendimiento reduciendo el número de dispositivos de almacenamiento para almacenar la misma cantidad de datos.
* Reducir los costes de almacenamiento gracias a la optimización del uso de los sistemas de almacenamiento.
* Reduce la huella de carbono mediante el uso de energías renovables en los centros de datos.
* Mejorar la eficiencia energética mediante la implementación de políticas de eficiencia energética.

