---
settings:
  name: Digital Advisor
  release_notes_autogen:
    release_notes_repo: console-relnotes
  harmony_integration: maestro
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de Digital Advisor
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades
      url: "/reference_new_activeiq.html"
    - title: Limitaciones conocidas
      url: "/reference_limitations_activeiq.html"
  - title: Manos a la obra
    entries:
    - title: Inicio rápido para Digital Advisor
      url: "/concept_getting_started_2.html"
    - title: Conozca las funciones del Digital Advisor
      url: "/concept_understand_activeiq_features.html"
    - title: Acceda a Digital Advisor en la consola de NetApp
      url: "/digital-advisor-integration-with-console.html"
    - title: Más información sobre el asesor digital
      url: "/concept_key_terms.html"
    - title: Obtenga más información sobre AutoSupport
      url: "/concept_autosupport.html"
    - title: Inicie sesión en Digital Advisor
      url: "/task_login_activeiq.html"
    - title: Aprovisionar lista de observación
      entries:
      - title: Obtenga más información sobre las listas de seguimiento
        url: "/concept_overview_dashboard.html"
      - title: Cree una lista de observación
        url: "/task_add_watchlist.html"
      - title: Administrar una lista de observación
        url: "/task_manage_watchlists.html"
    - title: Preguntas frecuentes para Digital Advisor
      url: reference_aiq_faq.html
  - title: Utilice el Asesor digital
    entries:
    - title: Analizar atributos de bienestar
      entries:
      - title: Aprenda sobre el widget de bienestar
        url: "/concept_overview_wellness.html"
      - title: Visualizar los riesgos del sistema de almacenamiento y tomar medidas
          correctivas
        url: "/task_view_risk_and_take_action.html"
      - title: Detectar riesgos de seguridad y tomar medidas correctivas
        url: "/task_increase_protection_against_hackers_and_Ransomware_attacks.html"
      - title: Proteja los sistemas de almacenamiento de los riesgos de ransomware
        url: "/task_protect_systems_against_ransomware_risks.html"
      - title: Analizar los atributos de bienestar y reconocer los riesgos
        url: "/task_view_and_acknowledge_risks.html"
      - title: Ver el historial de riesgos del sistema de almacenamiento
        url: "/task_view_wellness_history.html"
      - title: Visualice los riesgos y mitigue los riesgos utilizando Unified Manager
          o Ansible Playbook
        url: "/task_view_risks_remediated_unified_manager.html"
      - title: Utilice Digital Advisor para solucionar los riesgos críticos identificados
        url: "/task_avoid_the_downtime_and_possible_data_loss.html"
      - title: Suscribirse a notificaciones sobre el estado del sistema de almacenamiento
        url: "/task_subscribe_to_wellness_review_email.html"
      - title: Identificar renovaciones de software y hardware para el sistema de
          almacenamiento
        url: "/task_renew_software_and_hardware.html"
      - title: Visualice el estado de los clústeres y nodos mediante el widget ClusterViewer
        url: "/task_analyze_wellness_clusters_and_nodes.html"
    - title: Analizar la sostenibilidad del sistema de almacenamiento
      entries:
      - title: Aprende sobre sostenibilidad
        url: "/learn-about-sustainability.html"
      - title: Acceda al panel de control de sostenibilidad
        url: "/get_started_sustainability_dashboard.html"
      - title: Conozca las funciones del panel de sustentabilidad
        url: "/sustainability-dashboard-overview.html"
      - title: Mejorar la puntuación de sostenibilidad del sistema de almacenamiento
        url: "/improve_sustainability_score.html"
    - title: Genere un plan de actualización
      entries:
      - title: Obtenga información sobre cómo generar un plan de actualización de
          ONTAP
        url: "/upgrade_advisor_overview.html"
      - title: Generar un plan de actualización de ONTAP para clústeres individuales
          y múltiples
        url: "/generate_upgrade_plan_single_multiple_clusters.html"
      - title: Ver recomendaciones de actualización de firmware
        url: "/view-firmware-update-recommendations.html"
    - title: Ver detalles del sistema
      entries:
      - title: Ver detalles del inventario del sistema de almacenamiento
        url: "/task_view_inventory_details.html"
      - title: Ver los datos de máquinas virtuales disponibles en Data Infrastructure
          Insights
        url: "/task-integrating-with-cloud-insights-to-view-vm-details.html"
      - title: Vea casos de soporte y detalles del sistema de almacenamiento con el
          widget Información valiosa
        url: "/task_view_valuable_insight_widget.html"
      - title: Vea el uso de la capacidad con la suscripción a NetApp Keystone
        url: "/view_keystone_capacity_utilization.html"
    - title: Identifique de manera proactiva los requisitos del sistema
      entries:
      - title: Administre los requisitos de capacidad del sistema de almacenamiento
          con el widget Planificación
        url: "/concept_overview_planning.html"
      - title: Identificar sistemas de almacenamiento que se acercan a los límites
          de capacidad
        url: "/task_identify_capacity_system.html"
      - title: Administrar los umbrales de capacidad de almacenamiento de volumen
        url: "/task_avoid_a_volume_filling_up_to_prevent_an_outage.html"
      - title: Determinar si se recomienda una actualización tecnológica para el sistema
          de almacenamiento
        url: "/evaluate-tech-refresh.html"
      - title: Renovar el software y hardware del sistema de almacenamiento
        url: "/task_renew_software_and_hardware.html"
    - title: Analice el estado del sistema de almacenamiento con recomendaciones en
        la nube
      url: "/task-informed-decisions-based-on-cloud-recommendations.html"
    - title: Identificar la desviación de configuración
      entries:
      - title: Detectar desviaciones de configuración para el sistema de almacenamiento
        url: "/concept_overview_config_drift.html"
      - title: Agregar una plantilla de deriva de configuración para el sistema de
          almacenamiento
        url: "/task_add_config_drift_template.html"
      - title: Comparar plantillas de deriva de configuración
        url: "/task_compare_config_drift_template.html"
      - title: Generar un informe de cronología de desviaciones de configuración
        url: "/task_generate_drift_timeline_report.html"
      - title: Administrar plantillas de desviación de configuración
        url: "/task_manage_template.html"
    - title: Mejorar la eficiencia y el rendimiento del sistema de almacenamiento
      entries:
      - title: Visualice los ahorros en capacidad y eficiencia de almacenamiento
        url: "/task_analyze_storage_efficiency.html"
      - title: Ver gráficos de rendimiento del sistema de almacenamiento
        url: "/task_view_performance_graphs.html"
    - title: Analizar la salud del sistema de almacenamiento
      entries:
      - title: Obtenga más información sobre el panel de control de salud
        url: "/concept_understand_health_check_dashboard.html"
      - title: Comenzar con la consola de comprobación de estado
        url: "/concept_get_started_with_health_check_dashboard.html"
      - title: Renovar contratos de soporte
        url: "/task_renew_support_contracts_for_your_systems.html"
    - title: Actualice para optimizar su base instalada
      entries:
      - title: Oferta de soporte de actualización
        url: "/task_upgrade_support_offering.html"
      - title: Actualice el firmware de AFF y FAS mediante Ansible Playbook
        entries:
        - title: Descargue el paquete de firmware Ansible AFF y FAS
          url: "/task_update_AFF_FAS_firmware.html"
        - title: Actualice el firmware de AFF y FAS mediante un paquete Ansible (usuarios
            experimentados)
          url: "/task_install_execute_firmware_update_exp_user.html"
        - title: Instalar y ejecutar el paquete de automatización de Ansible (principiantes)
            firmware de AFF y FAS
          entries:
          - title: Alojar archivos de firmware AFF y FAS en un servidor web
            url: "/task_hosting_firmware_files_using_web_server.html"
          - title: Actualice el archivo de inventario para la actualización del firmware
              AFF y FAS
            url: "/concept_working_with_inventory_file.html"
          - title: Ejecute el playbook de Ansible usando la imagen Docker de NetApp
            url: "/task_execute_ansible_playbook_using_docker.html"
          - title: Ejecute el playbook de Ansible sin la imagen de Docker de NetApp
            url: "/task_execute_ansible_playbook_without_docker.html"
          - title: Validar la instalación del firmware AFF y FAS en el sistema de
              almacenamiento
            url: "/task_validate_firmware_installation.html"
    - title: Integrar datos mediante API
      entries:
      - title: Conozca los servicios API de Digital Advisor
        url: "/concept_overview_API_service.html"
      - title: Generar tokens para utilizar los servicios de API de Digital Advisor
        url: "/task_generate_tokens_API_services.html"
      - title: Utilice el catálogo de API de Digital Advisor para ejecutar las API
        url: "/task_view_API_catalog.html"
    - title: Generar informes personalizados
      entries:
      - title: Conozca los informes de Digital Advisor
        url: "/concept_report_types.html"
      - title: Generar o programar un informe
        url: "/task_generate_reports.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/reference_ansible_troubleshoot_feedback_support.html"
    - title: Obtenga ayuda
      url: "/concept_get_more_information.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: NetApp Console
  repo: console-family
