---
sidebar: sidebar 
permalink: task_identify_capacity_system.html 
keywords: capacity, space, increase, ontap systems, storagegrid, storage expansion 
summary: Proporciona información para aumentar la capacidad del sistema. 
---
= Identifique los sistemas de almacenamiento que se acercan a los límites de capacidad en Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Identifique de manera proactiva los sistemas que alcanzan los límites de capacidad y envíe una solicitud para aumentar la capacidad de su sistema de almacenamiento.

En ONTAP, se pueden ver sistemas que han superado el 90% de su capacidad o que deben superar el 90% de su capacidad en 1, 3 y 6 meses. En StorageGRID, se pueden ver sistemas que han superado el 70% de su capacidad o que deben superar el 70% de su capacidad en 1, 3 y 6 meses.

.Pasos
. En el widget *Planning*, selecciona *Storage Expansion*.
+
De forma predeterminada, se muestran los sistemas de ONTAP que han superado el 90 % de su capacidad o que se acercan al 90 %.

. Selecciona la pestaña *StorageGRID* para ver los sistemas StorageGRID que han superado el 70 % de su capacidad o que se están acercando al 70 % de su capacidad.
. Seleccione los sistemas para los que desea aumentar la capacidad.
. Selecciona *Ver previsión de capacidad* para consultar la previsión de capacidad para los próximos 6 meses.
. Selecciona *Request to Add Capacity*.
. De manera opcional, introduzca cualquier comentario.
. Selecciona *Enviar* para enviar la solicitud al equipo de almacenamiento de NetApp para que te ayude con la ampliación del almacenamiento de los sistemas seleccionados.

