---
sidebar: sidebar 
permalink: task_view_inventory_details.html 
keywords: inventory, platforms, systems, clusters, sites 
summary: Proporciona información sobre el inventario general de su propiedad. 
---
= Vea los detalles del inventario de su sistema de almacenamiento en Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El widget *Inventario* le proporciona un resumen de todos los sistemas y los conmutadores con soporte técnico que posee.  Esto incluye productos habilitados y no habilitados para Digital Advisor .

También puede generar el informe de la lista de observación seleccionada y enviarlo por correo electrónico a un máximo de 5 destinatarios.

video::ttbpbT5uTBI[youtube,width=848,height=480]


[[view-system-details]]
== Ver detalles del sistema

.Pasos
. En el widget *Inventario*, selecciona *Sistemas* para ver la información del sistema de todas las plataformas o selecciona el tipo de plataforma y luego selecciona *Sistemas* para ver los sistemas específicos de esa plataforma.
. Selecciona el nodo o el clúster para ver información detallada sobre el sistema.
. Selecciona *Descargar* para descargar el informe *Inventory* y consultar los detalles del sistema en formato .xls.
. Selecciona *Descargar* para descargar el informe *Ansible Inventory* y consultar los detalles del sistema en los formatos .yml e .ini a nivel de región o de sitio.
+
Los archivos de inventario de Ansible pueden utilizarse con archivos personalizados del libro de aplicaciones de Ansible para hacer cambios en la configuración de la infraestructura.





[[view-support-entitled-switch-details]]
== Ver detalles del cambio de soporte autorizado

.Pasos
. En el widget *Inventario*, selecciona *Conmutadores con derecho a asistencia* para ver información sobre todos los conmutadores con derecho a asistencia.

