---
sidebar: sidebar 
permalink: task_view_API_catalog.html 
keywords: API Catalog, APIs, integrate data, view catalog 
summary: Proporciona información acerca de las API disponibles en el catálogo de API. 
---
= Utilice el catálogo de API de Digital Advisor para ejecutar las API
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El catálogo de la API permite examinar las categorías y las API disponibles dentro de cada una de esas categorías.

Mediante un token de acceso válido y las entradas correctas para los campos requeridos, puede realizar una llamada de prueba para una API.



== Acceder a las API de GraphQL

.Pasos
. En el menú *Enlaces rápidos*, haga clic en *Servicios API*.
. Hacer cliclink:https://activeiq.netapp.com/catalog/internal/api-reference/introduction["Navegar"] bajo el ícono *Catálogo API*.
+
Se muestra el catálogo de API.

. Haga clic en *GraphQL* y revise la documentación.
. Pruebe las API de GraphQL utilizando las consultas de muestra listas para ejecutar enlink:https://studio.apollographql.com/public/ActiveIQ-Graph-Prd-API/variant/current/explorer?collectionId=251c50ce-797e-4549-bb9c-f6557ef5a176OPERATION_COLLECTIONfocusCollectionId=251c50ce-797e-4549-bb9c-f6557ef5a176["Digital Advisor GraphQL Studio"^] .
. Proporcione un token de usuario seleccionando el campo de autorización en el encabezado de la solicitud de API
. Proporcione las variables requeridas
. Ejecute la consulta y revise el resultado




== Acceder a las API REST

.Pasos
. En el menú *Enlaces rápidos*, haga clic en *Servicios API*.
. Hacer cliclink:https://activeiq.netapp.com/catalog/internal/api-reference/introduction["Navegar"] bajo el ícono *Catálogo API*.
+
Se muestra el catálogo de API.

. Haga clic en *ActiveIQ-Public* y seleccione cualquier API
. En la parte superior de la página, deslice el botón hacia “experimento”.
. En la navegación de la izquierda, expanda las categorías y seleccione cualquier API para ver información detallada.
. Expanda la API.
. Haga clic en el botón *probar fuera* de la derecha.
. Proporcione los parámetros necesarios y haga clic en *Ejecutar* para ver los resultados.
+
También puede examinar la sección *Responses* de la API para entender los datos que se devolverán mejor. Puede hacer clic en *valor de ejemplo* para ver el formato de los datos o hacer clic en *Modelo* y hacer clic en los caretas para expandir las secciones para ver la definición de cada elemento.



Al deslizar el botón hacia la vista *Código*, puede ver ejemplos de código en varios idiomas.
