---
sidebar: sidebar 
permalink: task_protect_systems_against_ransomware_risks.html 
keywords: ransomware, risks, ransomware risks 
summary:  
---
= Proteja los sistemas de almacenamiento administrados por Digital Advisor de los riesgos de ransomware
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Al iniciar sesión en el Asesor digital, puede ver las *Acciones* resaltadas en el widget *Seguridad y defensa contra ransomware*, que muestra el recuento de riesgos.

Puede ver los riesgos de creación, retención y FPolicy de ONTAP y, a continuación, realizar acciones para corregirlos.

.Pasos
. Inicie sesión en Digital Advisor.
. Haga clic en *Acciones* en el widget *Seguridad y defensa contra ransomware*.
. Desactive la casilla de verificación *Vulnerabilidades de seguridad*.
. Para los riesgos que se muestran, compruebe el nivel de impacto y siga las acciones recomendadas.
. Haga clic en la ficha riesgos únicos y en el enlace de la columna *Acción Correctiva*.
. Haga clic en la ficha *sistemas afectados* para ver sistemas con riesgos.
. Siga las acciones de corrección que se recomiendan para proteger los sistemas.

