---
sidebar: sidebar 
permalink: task_identify_capacity_system.html 
keywords: capacity, space, increase, ONTAP systems, StorageGRID 
summary: Proporciona información para aumentar la capacidad del sistema. 
---
= Identifique los sistemas de almacenamiento que se acercan a los límites de capacidad en Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Identifique de manera proactiva los sistemas que alcanzan los límites de capacidad y envíe una solicitud para aumentar la capacidad de su sistema de almacenamiento.

En ONTAP, se pueden ver sistemas que han superado el 90% de su capacidad o que deben superar el 90% de su capacidad en 1, 3 y 6 meses. En StorageGRID, se pueden ver sistemas que han superado el 70% de su capacidad o que deben superar el 70% de su capacidad en 1, 3 y 6 meses.

.Pasos
. En el widget *Planning*, haz clic en *Adición de capacidad*.
+
De forma predeterminada, se muestran los sistemas de ONTAP que han superado el 90 % de su capacidad o que se acercan al 90 %.

. Haga clic en la pestaña *StorageGRID* para ver los sistemas StorageGRID que han superado el 70% de capacidad o que están cerca del 70% de capacidad.
. Seleccione los sistemas para los que desea aumentar la capacidad.
. Haga clic en *Ver pronóstico de capacidad* para ver el pronóstico de capacidad para los próximos 6 meses.
. Haga clic en *Solicitar para agregar capacidad*.
. De manera opcional, introduzca cualquier comentario.
. Haga clic en *Enviar* para enviar la solicitud al equipo de almacenamiento de NetApp para ayudar con la adición de capacidad para los sistemas seleccionados.

