---
sidebar: sidebar 
permalink: task-integrating-with-cloud-insights-to-view-vm-details.html 
keywords: Cloud Insights, VMs, virtual machines 
summary: Proporciona información acerca de las máquinas virtuales en Cloud Insights 
---
= Integración con Cloud Insights para ver los detalles de las máquinas virtuales
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
El asesor digital ahora se integra en la versión básica de Cloud Insights para proporcionar a los clientes un inventario de toda la pila y comprobaciones de interoperabilidad.

Las ventajas de esta integración son:

* Supervisión SaaS simplificada de ONTAP
* Visibilidad de la supervisión de toda la pila de VMware
* Ahorros en productividad para los clientes mediante comprobaciones de interoperabilidad automatizadas que ayudan en la planificación de actualizaciones de ONTAP. Esto da como resultado actualizaciones de ONTAP más fluidas y reduce los riesgos de incompatibilidad con los hosts.



NOTE: Esta función solo está disponible para contratos de actualización de SupportEdge Advisor, SupportEdge Expert y Asesor digital.

.Pasos
. En el widget *Inventario*, haga clic en *Máquinas virtuales* para ver los datos disponibles en Cloud Insights.
. Haga clic en la ficha *Descripción general de la máquina virtual*.
. Haga clic en el *recuento de hosts ESX* para ver información sobre el host.
. Haga clic en *Nombre ESX* para navegar hasta Cloud Insights para ver más información.

