---
sidebar: sidebar 
permalink: task_protect_systems_against_ransomware_risks.html 
keywords: ransomware, risks, ransomware risks 
summary:  
---
= Proteja los sistemas de almacenamiento administrados por Digital Advisor de los riesgos de ransomware
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Al iniciar sesión en el Asesor digital, puede ver las *Acciones* resaltadas en el widget *Seguridad y defensa contra ransomware*, que muestra el recuento de riesgos.

Puedes ver los riesgos relacionados con la creación y retención de instantáneas y los riesgos de ONTAP FPolicy, y luego tomar medidas para solucionarlos.

.Pasos
. Inicie sesión en Digital Advisor.
. Selecciona *Acciones* en el widget *Security & Ransomware Defense*.
. Desactive la casilla de verificación *Vulnerabilidades de seguridad*.
. Para los riesgos que se muestran, compruebe el nivel de impacto y siga las acciones recomendadas.
. Selecciona la pestaña *Riesgos específicos* y selecciona el enlace en la columna *Medida correctiva*.
. Selecciona la pestaña *Sistemas afectados* para ver los sistemas que presentan riesgos.
. Selecciona las medidas correctivas recomendadas para proteger los sistemas.

