---
sidebar: sidebar 
permalink: task-integrating-with-cloud-insights-to-view-vm-details.html 
keywords: Cloud Insights, VMs, virtual machines, Data Infrastructure Insights 
summary: Proporciona información sobre las máquinas virtuales en Data Infrastructure Insights 
---
= Utilice Digital Advisor para ver los datos de máquinas virtuales disponibles en Data Infrastructure Insights
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Digital Advisor ahora está integrado con la versión básica de Data Infrastructure Insights para proporcionar un inventario completo y controles de interoperabilidad a los clientes.

Las ventajas de esta integración son:

* Supervisión SaaS simplificada de ONTAP
* Visibilidad de la supervisión de toda la pila de VMware
* Ahorros en productividad para los clientes mediante comprobaciones de interoperabilidad automatizadas que ayudan en la planificación de actualizaciones de ONTAP. Esto da como resultado actualizaciones de ONTAP más fluidas y reduce los riesgos de incompatibilidad con los hosts.



NOTE: Esta función solo está disponible para contratos de actualización de SupportEdge Advisor, SupportEdge Expert y Asesor digital.

.Pasos
. En el widget *Inventario*, haga clic en *Máquinas virtuales* para ver los datos disponibles en Data Infrastructure Insights.
. Haga clic en la ficha *Descripción general de la máquina virtual*.
. Haga clic en el *recuento de hosts ESX* para ver información sobre el host.
. Haga clic en el *Nombre de ESX* para navegar a Data Infrastructure Insights para ver más información.

