---
sidebar: sidebar 
permalink: task_view_and_acknowledge_risks.html 
keywords: wellness, performance, efficiency, availability, capacity, security vulnerabilities, protection, protect, acknowledge, unacknowledge, disregard 
summary: Ofrece información para ver y analizar el estado de su sistema de almacenamiento y reconocer los riesgos. 
---
= Analice los atributos de bienestar en Digital Advisor y reconozca los riesgos
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede analizar los atributos de estado del sistema de almacenamiento consultando las acciones y riesgos asociados con él. Debe ver las acciones correctivas y mitigar manualmente el riesgo.

.Pasos
. Selecciona el widget de atributos de bienestar en el panel de control o selecciona *Ver todas las acciones* para ver la lista de todas las acciones y riesgos.
. Consulte las *acciones* y *riesgos* asociadas con el atributo wellness.
. Selecciona *Acciones* para ver los riesgos asociados a las acciones, selecciona *Riesgos* para ver todos los riesgos o selecciona *Sistemas afectados* para ver los sistemas que requieren atención.
. Selecciona el riesgo para ver el resumen del riesgo.
. Selecciona *Ack* para reconocer el riesgo.
+
La información detallada del resumen de riesgos se proporciona junto con acciones correctivas que deben realizarse manualmente para mitigar el riesgo.

. Si no deseas o no puedes mitigar el riesgo en este momento, introduce los valores en los campos y selecciona *Acknowledge*.
+
El riesgo se añadirá a los riesgos reconocidos.




NOTE: Si ya no quieres que se reconozca un riesgo, puedes ignorar el riesgo seleccionando *Desreconocer* y siguiendo los mismos pasos.
