---
sidebar: sidebar 
permalink: task_analyze_storage_efficiency.html 
keywords: renew, hardware, software 
summary: Proporciona información para renovar el software y el hardware del sistema de almacenamiento. 
---
= Analizar el ahorro en capacidad y la eficiencia del almacenamiento
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Puede ver los detalles de capacidad y el ahorro de eficiencia del almacenamiento del sistema y tomar las acciones correspondientes. La información sobre la capacidad y la eficiencia del almacenamiento puede verse en el nivel de un clúster o de un nodo.


NOTE: Esta función no es compatible con los sistemas E-Series.

La consola de capacidad muestra los detalles de capacidad y la previsión de capacidad del sistema. La previsión de capacidad utiliza la información de capacidad histórica para identificar el uso de cada sistema. Basándose en los datos históricos (los datos de un año, si están disponibles) de la capacidad utilizada y asignada, el algoritmo considera la utilización actual de cada sistema y genera un pronóstico para la utilización del sistema en los próximos 1 a 6 meses.

La consola de eficiencia del almacenamiento muestra la proporción de eficiencia del almacenamiento, el espacio lógico utilizado, el espacio físico utilizado y los datos totales ahorrados para los sistemas de almacenamiento que ejecutan ONTAP 9.1 y versiones posteriores. La ratio de eficiencia y el ahorro se pueden ver con y sin las copias Snapshot para sistemas AFF, sistemas no AFF, o ambos. El ahorro total en el almacenamiento del cliente puede verse por función de eficiencia, como la deduplicación de volúmenes, la compresión de volúmenes, la compactación, los volúmenes FlexClone y las copias Snapshot. También puede ver los 5 sistemas de almacenamiento principales con la mejor ratio de eficiencia.

video::8Ge3_0qlyxA[youtube,width=848,height=480]
.Pasos
. En el panel izquierdo, haga clic en *capacidad y eficiencia*.
+
De forma predeterminada, se selecciona la ficha *capacidad*.

. Consulte los detalles de capacidad en el nivel del clúster y del nodo.
+
.. Vea el pronóstico de capacidad en el nivel del nodo.
+
Para los sistemas ONTAP, la información sobre la capacidad BRUTA está disponible en ClusterViewer.

.. Haga clic en *Añadir capacidad* para enviar una notificación a NetApp o a su partner para añadir capacidad.


. Vea la eficiencia del almacenamiento y el ahorro de datos del sistema de almacenamiento.
+
.. Si la proporción de eficiencia del almacenamiento de su sistema de almacenamiento es superior a la media en la proporción de eficiencia del almacenamiento, haga clic en *Comparta su caso de cliente* para informarnos de las mejores prácticas seguidas.
.. Si la tasa de eficiencia del almacenamiento de su sistema de almacenamiento es inferior a la tasa media de eficiencia del almacenamiento, haga clic en *Póngase en contacto con nosotros* para informarnos de las configuraciones de su sistema de almacenamiento.




Para obtener más información sobre la capacidad y la eficiencia del almacenamiento, consulte link:reference_aiq_faq.html["Preguntas frecuentes sobre el Asesor Digital"].
