---
sidebar: sidebar 
permalink: task_view_wellness_history.html 
keywords: wellness history, risks, wellness, view all actions, risk history 
summary: Proporciona información sobre los riesgos del sistema y cómo ver la historia del bienestar. 
---
= Consulte el historial de riesgos de su sistema de almacenamiento en Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede visualizar los riesgos del sistema de almacenamiento que ocurrieron en los últimos tres meses, para que pueda saber cómo les está yendo con el tiempo.

Estos riesgos se clasifican en cuatro tipos de riesgos: *Sin resolver*, *Nuevo*, *resuelto* y *reconocido*. Se representan con colores diferentes. El resumen de estos riesgos se representa a través de un gráfico *Historial de riesgos*.

.Pasos
. En el panel de control, en el panel *Wellness*, selecciona *View All Actions*.
. Selecciona *Historial de bienestar*.
. En el gráfico *Historial de riesgos*, selecciona la categoría cuyo historial de riesgos quieras consultar.
+
Al pasar el cursor por encima de las barras de color, se muestra información sobre el número de riesgos en cada categoría. Al seleccionar la categoría de riesgo correspondiente, la información se muestra en la tabla *Información sobre riesgos*.

+
También puede descargar un resumen de riesgos en una hoja de Excel.


