---
sidebar: sidebar 
permalink: task_analyze_storage_efficiency.html 
keywords: capacity, storage efficiency, data reduction, savings 
summary: Consulta los detalles sobre la capacidad y el ahorro en eficiencia de almacenamiento de tu sistema de almacenamiento. 
---
= Vea los ahorros en capacidad y eficiencia de almacenamiento en Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede ver los detalles de capacidad y el ahorro de eficiencia del almacenamiento del sistema y tomar las acciones correspondientes. La información sobre la capacidad y la eficiencia del almacenamiento puede verse en el nivel de un clúster o de un nodo.


NOTE: Esta función no es compatible con los sistemas E-Series.

El panel de control de capacidad muestra los detalles de capacidad y la previsión de capacidad de tu sistema. La previsión de capacidad utiliza información histórica de capacidad para identificar la utilización de cada sistema. Basándose en los datos históricos (los de un año, si están disponibles) de la capacidad utilizada y asignada, el algoritmo considera la utilización actual de cada sistema y genera una previsión de la utilización del sistema para los próximos 1 a 6 meses.

El panel de control de eficiencia de almacenamiento muestra la proporción de reducción de datos, el espacio lógico utilizado, el espacio físico utilizado y el total de datos ahorrados. Puedes ver la proporción de reducción de datos y el ahorro con y sin copias de snapshot para sistemas AFF, sistemas que no son AFF o ambos. El ahorro total de datos en el almacenamiento del cliente se puede ver por función de eficiencia, como la deduplicación de volúmenes, la compresión de volúmenes, la compactación, los volúmenes FlexClone y las copias de snapshot. Puedes ver los 5 sistemas de almacenamiento con la mejor proporción de eficiencia. También puedes ver la eficiencia de SAN y NAS sin copias de snapshot a nivel de nodo para sistemas ONTAP, incluidos AFF A-Series, AFF C190, All SAN Array y FAS500.

video::8Ge3_0qlyxA[youtube,width=848,height=480]
.Pasos
. En el panel de la izquierda, selecciona *Capacidad y eficiencia*.
+
De forma predeterminada, se selecciona la ficha *capacidad*.

. Consulte los detalles de capacidad en el nivel del clúster y del nodo.
+
.. Vea el pronóstico de capacidad en el nivel del nodo.
+
Para los sistemas ONTAP, la información sobre la capacidad BRUTA está disponible en ClusterViewer.



. Selecciona *Add Capacity* para enviar una notificación a NetApp o a tu socio para añadir capacidad.
. Vea la eficiencia del almacenamiento y el ahorro de datos del sistema de almacenamiento.
+
.. Si el índice de eficiencia de almacenamiento de tu sistema de almacenamiento es superior al índice medio de eficiencia de almacenamiento, selecciona *Comparte tu historia de éxito* para contarnos cuáles son las mejores prácticas que has seguido.
.. Si el índice de eficiencia de almacenamiento de tu sistema de almacenamiento es inferior al índice medio de eficiencia de almacenamiento, selecciona *Contact Us* para contarnos las configuraciones de tu sistema de almacenamiento.




Para obtener más información sobre la capacidad y la eficiencia del almacenamiento, consulte link:reference_aiq_faq.html["Preguntas frecuentes sobre el Asesor Digital"].
