---
sidebar: sidebar 
permalink: task_subscribe_to_wellness_review_email.html 
keywords: wellness, wellness review subscription, unsubscribe, supportedge expert, supportedge advisor 
summary:  
---
= Suscríbete a las notificaciones sobre el estado del sistema de almacenamiento de Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/



NOTE: La función Wellness Review ha quedado obsoleta y ya no está disponible en Digital Advisor desde julio de 2026.

Puedes suscribirte al correo electrónico de revisión de estado para recibir mensualmente un resumen del estado de bienestar, los sistemas de almacenamiento que se acercan a sus fechas de renovación y los sistemas de almacenamiento que requieren una actualización para los productos de NetApp en tu base instalada. Recibirás un correo electrónico de revisión de estado de bienestar para que puedas ver un resumen mensual y tomar acción para tus sistemas de almacenamiento.

También tienes opciones para ver, editar, compartir y eliminar tus suscripciones. En cualquier momento, si decides que no quieres recibir el correo electrónico, también puedes darte de baja.

Una vez activada la suscripción, deberá seleccionar una fecha de inicio al agregar una suscripción. El resumen mensual del correo electrónico ofrece una vista de las acciones de comprobación del estado, renovación, actualización y estado excepcionales. Puede confirmar la dirección de correo electrónico y que se ha enviado el correo electrónico a la dirección de correo electrónico especificada. También tiene la opción de eliminar suscripciones.


NOTE: Esta función solo está disponible a través de las ofertas de servicio SupportEdge Advisor y SupportEdge Expert de NetApp.

.Pasos
. En el panel izquierdo, haga clic en *Revisión de bienestar*.
. Haga clic en *Agregar suscripción*.
. Proporcione la información necesaria en los campos *Nombre de los campos Suscripción*, *elegir categoría*, *Buscar cliente* y *correo electrónico* del cuadro de diálogo *Agregar nueva suscripción*.
. Haga clic en *Suscribirse*.
+
Una vez que la suscripción se haya realizado correctamente, recibirá un mensaje *Suscripción ha sido añadida*.


