---
sidebar: sidebar 
permalink: view-firmware-update-recommendations.html 
keywords: upgrade advisor, firmware recommendations, storage firmware, sp bmc firmware, system files, security files 
summary: Consulta las recomendaciones de actualización del firmware de almacenamiento, el firmware de SP/BMC, los archivos del sistema y los archivos de seguridad. 
---
= Ver recomendaciones de actualización de firmware en Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ahora los clientes pueden ahorrar tiempo y esfuerzo al permitir que Control Tower actualice automáticamente sus sistemas con las últimas versiones de firmware, eliminando la necesidad de intervención manual o programación. Esta actualización reduce el riesgo de encontrarse con problemas debido a versiones de firmware desactualizadas o incompatibles, lo que garantiza un rendimiento, estabilidad y seguridad óptimos del sistema.

Los clientes recibirán notificaciones y alertas oportunas sobre el estado de las actualizaciones de firmware, con opciones para habilitar AutoSupport y la configuración de actualización automática.

.Pasos
. En la página del panel de control, selecciona *Otras recomendaciones* en el widget *Upgrade Advisor*.
. Selecciona *Ver recomendaciones* para ver la lista de recomendaciones.
. En la columna *Estado de la actualización*, selecciona *Ver progreso* para ver los clústeres que cumplen los requisitos para una actualización.
. En caso de que surja algún problema, selecciona los enlaces correspondientes para consultar los pasos que debes seguir para solucionar los problemas.

